### ISSUE TITLE
🎮 👾 🎮 arcade activity

### ISSUE THREAD

**Issue by esdalee** [mgilliland23/UpselfMobile#18]
there is an issue with the game for now... after the game ends we need to:

reset stats i.e. click/moves/...
reshuffle the array
the problem with 2 is that the array reshuffle is in the parent component and we would need to bind the function and update the state once we call this from the child component.

**Comment by costargc** [comment]
there is an issue with the game for now... after the game ends we need to:
1) reset stats i.e. click/moves/...
2) reshuffle the array

the problem with 2 is that the array reshuffle is in the parent component and we would need to bind the function and update the state once we call this from the child component.

**Comment by mgilliland23** [comment]
I’m pretty sure I know how to solve this. I will look into tonight

**Comment by costargc** [comment]
I think you have a lot with you @mgilliland23 ... I can take on that one! I'm just documenting what I need to do 😄

**Comment by costargc** [comment]
game done!
