### ISSUE TITLE
menu page

### ISSUE THREAD

**Issue by esdalee** [mgilliland23/UpselfMobile#19]

**Comment by costargc** [comment]
I still think that we can improve the menu page and that we should invest some more time in making it cool and modern.


I would suggest that we:
1. add a loading screen with the logo and with an initial msg (can be the same as the original design from matt)
2. After the login page... I would prefer to have all content be displayed as a carousel where its only showing on screen one option at a time:
ex.: https://www.npmjs.com/package/react-native-snap-carousel

(if we could add a footer with the options as well that would be great!)

![image](https://user-images.githubusercontent.com/25669140/65072767-88b20780-d95f-11e9-93cd-4dcfe827d140.png)

**Comment by costargc** [comment]
that way ... we can avoid having the logo in the menu page (as the loading screen would show it) ... and we would simplify what users can see on screen.

one upsy/function per card.

**Comment by costargc** [comment]
also... the pink colour is the same as upsy cheeks... that seems a little odd.

**Comment by mgilliland23** [comment]
Agreed. The bottom of the screen is not a good spot to have icons either as it is more difficult to click if using phone with just 1 hand (which the majority of people do) And for you the background of the carousel I think we could make it transparent and it will make the page flow better
